version: "3.9"

services:
    postgres:
        container_name: postgres
        image: postgres
        restart: always
        ports:
            - 5433:5433
        environment:
            - POSTGRES_DB=ignitedb
            - POSTGRES_USER=postgres
            - POSTGRES_PASSWORD=docker
            - PGPORT=5433
            - POSTGRES_HOST_AUTH_METHOD=md5
        volumes:
            - pgdata:/data/postgres
    api_ignite:
        container_name: api_ignite
        build: .
        ports:
            - 3333:3333
        volumes:
            - .:/usr/api
        links:
            - postgres
        depends_on: 
            - postgres 

            
volumes:
    pgdata:
        driver: local
